#!/usr/local/bin/perl

use strict;
use warnings;

use blib;

use Win32::Process::Info qw{NT};

use Win32::Process::Info qw{WMI};

foreach my $variant (qw{NT WMI}) {
    print $variant, "\t",
	Win32::Process::Info->_available ($variant) || '', "\n";
}
